name: BuildingGame
author: GameZter
version: 1.0.0
description: BuildingGame for Timolia

main: at.timolia.gamezter.BuildingGame

commands:
  bginfo:
    description: Give information about the plugin
    usage: /bginfo
  bgup:
    description: Tps the player 10 blocks higher
    usage: /bgup <value>